### ISSUE TITLE
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

### ISSUE THREAD

**Issue by shizidushu** [xiaobai1217/RepetitionCounting#12]
I failed to run `python run_demo.py`.

```
(torch_rc) ubuntu@ubuntu:~/data/yong/projects/RepetitionCounting$ python run_demo.py
Traceback (most recent call last):
  File "run_demo.py", line 85, in <module>
    sample_rate = get_sr(spectrogram_ori, video1, model, audio_model, a_sr_model, v_sr_model)
  File "/home/ubuntu/data/yong/projects/RepetitionCounting/util.py", line 211, in get_sr
    outputs1 = v_sr_model(feat.detach(), audio_feat.flatten(1))
  File "/home/ubuntu/data/miniconda/envs/torch_rc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/data/miniconda/envs/torch_rc/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
```

**Comment by xiaobai1217** [comment]
Hi, you can simply check whether feat and audio_feat are on gpu device by ```print(feat.is_cuda)``` and ```print(audio_feat.is_cuda)```, then move the tensor on cpu to gpu to solve the problem
